### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by zhmingGIT** [duheng/Mozi#1]
Unable to resolve module `app/store/configure-store` from `/Users/zhming/work-dir/code/github/Mozi/src/root.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

**Comment by duheng** [comment]
本项目做了路径映射，依据你的报错信息请按以下步骤检查：
1.确保你的node_modules没有安装失败的，重点查看babel-plugin-module-resolver模块是否正确安装
2.查看你的跟目录有没有.babelrc 
3. 如果都没有问题请删除node_modules，用yarn重新安装一遍。

**Comment by mvpdream** [comment]
@zhmingGIT @duheng  报了一样的错误 按照你的方法试了 还是报错。。

**Comment by duheng** [comment]
电脑是什么系统

**Comment by duheng** [comment]
本项目是在mac系统下开发的，由于mac和windows命令相差太多，本项目暂不支持windows系统下的开发，windows系统开发的用户请自行更换cp（copy），alias地址映射请手动引用或者自行写一个bat代替

**Comment by zhmingGIT** [comment]
root.js下 这行没导入进来import configureStore from 'store/configure-store';

**Comment by duheng** [comment]
已解决：
1，请重新clone，或者git pull您的项目
2，重新编译查看效果。
