### ISSUE TITLE
不能运行  windows+android

### ISSUE THREAD

**Issue by tututututututu** [duheng/Mozi#2]
error: bundling failed: "Unable to resolve module `app/store/configure-store` from `D:\\rn\\mozi\\src\\root.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

**Comment by selectersky** [comment]
mac 电脑下也有同样问题：

```
Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (1/300), failed.
error: bundling failed: "Unable to resolve module `app/store/configure-store` from `/d/source/rn/Mozi/src/root.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

**Comment by duheng** [comment]
请确保babel-plugin-module-resolver包是正确安装的

**Comment by minsonl** [comment]
问题解决了么？一样遇到这个问题。。。

**Comment by duheng** [comment]
我找了几台电脑测试了一下都没问题，暂时没找到windows电脑，我就怀疑的问题修改了一下，帮忙测一下看好了没，谢谢了

**Comment by duheng** [comment]
已经修复，更新一下代码重新编译一下就可以了

**Comment by tututututututu** [comment]
好的 我试试
