### ISSUE TITLE
项目中 安卓端返回键 再按一次退出应用 有点问题

### ISSUE THREAD

**Issue by loss99** [duheng/Mozi#25]
if (nav.index === 0) {
      // alert(nav.index);进入任意页面 点击返回 都先进 这个判断,页面跳转了,但是 index 还是等于 0

**Comment by loss99** [comment]
也许 不判断 nav.index 就可以了

**Comment by duheng** [comment]
谢谢，会在下一个版本修复，

**Comment by duheng** [comment]
我看了一下这段代码，当初想的是当用户回退到首页的时候再按一次才退出应用。 我觉得这样比较合理一些，如果你的应用想在任何一个页面点两次系统返回键就退出应用的话可以把那个判断删掉就行

**Comment by duheng** [comment]
安卓返回已修复，有空更新一下看一下，谢谢您的反馈
