### ISSUE TITLE
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. 

### ISSUE THREAD

**Issue by SunAnle** [duheng/Mozi#28]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Mozi.xcodeproj

** BUILD FAILED **

The following build commands failed:
        Analyze /Users/sunal/Documents/Projects/Mozi/node_modules/react-native/ReactCommon/jsi/JSIDynamic.cpp normal x86_64
(1 failure)
. Run CLI with --verbose flag for more details.

作者知道这个坑怎么填吗？

**Comment by duheng** [comment]
这个跟项目没有关系，你本地之前没跑过0.57.8的项目，需要手动更新。建议你参考这篇文章更新一下https://www.codercto.com/a/69119.html
