### ISSUE TITLE
xcode 11.1启动不起来

### ISSUE THREAD

**Issue by flybrotheryao** [duheng/Mozi#38]
第一，直接用xcode打开 ios文件夹下的Mozi.xcodeproj，编译不成功，卡住。
第二，通过改nodemodule下的文件，使 yarn run ios 成功，一直这样，挑一串乱码在终端。
所以ios是运行不成功，我的mac系统是10.14,xcode是11.1

**Comment by duheng** [comment]
建议把证书修改成你自己的，然后clean一下，重新编译。
