### ISSUE TITLE
卡在启动页

### ISSUE THREAD

**Issue by zynote** [duheng/Mozi#4]
运行的时候直接卡在启动页无法操作, 也无法调试刷新

**Comment by duheng** [comment]
请完全按照我的文档启动

git clone https://github.com/duheng/Mozi.git

cd Mozi

yarn install

yarn start

yarn run ios (android)     

windows用户请用 react-native run-android 命令启动

如果还有报错请截图

**Comment by zynote** [comment]
就是按照这个来的,没有报错,就是卡在启动页一动不动,什么操作都不管用,安卓ios都试过了

**Comment by duheng** [comment]
![image](https://user-images.githubusercontent.com/4907067/33544678-ac3e3692-d916-11e7-8c08-c55d074aa3d0.png)
经过测试，未发现异常，请检查你自己的环境

**Comment by guanren** [comment]
试着把ios/build删除，重新react-native run-ios

**Comment by duheng** [comment]
已解决，git pull一下重新编译
