### ISSUE TITLE
卡在启动页面，报错如图

### ISSUE THREAD

**Issue by guanren** [duheng/Mozi#6]
![image](https://user-images.githubusercontent.com/16680025/33763616-2c469da6-dc4c-11e7-90bb-0664b82a607b.png)
[](url)

**Comment by guanren** [comment]
问题已解决nav.js中Routers这样导入import Routers from '../../routers/app';就对了

**Comment by duheng** [comment]
谢谢你的提醒，昨天修改的时候改漏了，已经修复了
