### ISSUE TITLE
android 没优化？这卡的还没navigator流畅！！

### ISSUE THREAD

**Issue by hxkuan** [duheng/Mozi#7]
android 没优化？这卡的还没navigator流畅！！react-navigation不是性能比较好吧，这是你写法出问题了？

**Comment by duheng** [comment]
请问您的电脑是不是升级macOS High Sierra了？

**Comment by duheng** [comment]
暂时没有对安卓做优化

**Comment by duheng** [comment]
是由于reducers/nav.js引起的，已经做了大概处理
