### ISSUE TITLE
你的demo里面是不是还没有集成适配啊？

### ISSUE THREAD

**Issue by RowgerGo** [duheng/Mozi#8]
例如，我看到你在config.js里面的TabNavigatorConfig把height写死为50

**Comment by duheng** [comment]
react-native会自己适配，不用关心这个，不用像web一样用rem去适配。如果遇到布局需要适配可以用百分比，也可以用flex

**Comment by RowgerGo** [comment]
抱歉，我说错了，是navigationOptions里面的headerStyle的height。不知道你是否有在多个模拟器上测试，height设置为64，在部分苹果机型上样式真的很丑，太高了

**Comment by duheng** [comment]
![image](https://user-images.githubusercontent.com/4907067/34250726-ac9a2c9e-e678-11e7-90cc-0c2b630cd75a.png)
我觉得这样正合适，这个你可以根据你们设计给的标准设置，跟适配没有关系

**Comment by RowgerGo** [comment]
好的，谢谢你啦
