### ISSUE TITLE
关于navigationOptions修改头部样式

### ISSUE THREAD

**Issue by RowgerGo** [duheng/Mozi#9]
![default](https://user-images.githubusercontent.com/14071531/34285991-cc686c98-e718-11e7-9b7d-29bedc5e29bc.png)
这样修改头部样式不生效吗

**Comment by RowgerGo** [comment]
``static navigationOptions = {
    headerTitle: '我的',
    headerStyle: {
      backgroundColor: '#4ECBFC',
    },
    headerTitleStyle: {
      color: 'red',
    },
  }

**Comment by duheng** [comment]
![head](https://user-images.githubusercontent.com/4907067/34300409-d4c775a6-e762-11e7-8026-388e3f993c7c.png)

已修复此bug，拉取最新版本，谢谢你的问题

**Comment by RowgerGo** [comment]
谢谢大佬即时更新啊，我rn基础很差的，然后这次项目会用到大佬的这套demo做底层，后面可以能会经常提issues。我尽量先自己多研究

**Comment by RowgerGo** [comment]
谢谢大佬即时更新啊，我rn基础很差的，然后这次项目会用到大佬的这套demo做底层，后面可以能会经常提issues。我尽量先自己多研究
